### ISSUE TITLE
Using CAM++ for Speaker Embeddings on 24kHz LibriTTS Data: Sampling Rate Adjustment for MFCC Calculation?

### ISSUE THREAD

**Issue by xjf-303** [modelscope/3D-Speaker#147]
@yfchenmodelscope
Hello! I'd like to run inference with CAM++ to extract speaker embeddings for the LibriTTS dataset. I noticed that the code converts the sampling rate to 16kHz during the MFCC feature computation. 
1.Could you please explain why this is done? 
2.Also, would it be possible to modify the code to work with the original 24kHz sampling rate of the LibriTTS dataset?
3. Or do you have any other suggestions? Thank you!

**Comment by yfchenlucky** [comment]
1. This is a common standard in speech processing because it captures the frequency range most relevant to human speech (up to 8kHz) while reducing computational load and storage requirements.
2. Yes, it is possible to modify the code to work with the original 24kHz sampling rate of the LibriTTS dataset. 
3. If 24kHz audio is used for training, then the test phase should also use 24kHz audio for better consistency and results. However, converting the 24kHz audio to 16kHz before training the model is generally a better approach, as it makes the model more universal and compatible with standard speech processing practices.
